# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.provision "shell", path: "./scripts/update.sh"

  config.vm.define "web" do |web|
    web.vm.hostname = "vagrant-intro-multi-web"

    web.vm.network "forwarded_port", guest: 80, host: 8887
    web.vm.network "private_network", ip: "10.0.0.10"

    web.vm.provision "shell", path: "./scripts/apache.sh"
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "vagrant-intro-multi-db"
    db.vm.network "private_network", ip: "10.0.0.20"

    db.vm.provision "shell", path: "./scripts/mariadb.sh"
  end
end
